[tools]
awscli = "2.28.22"
elixir = "1.18.3"
erlang = "27.3.3"
flutter = "3.29.3"
fzf = "0.65.2"
ghq = "1.8.0"
github-cli = "2.78.0"
go = "1.25.0"
lazydocker = "0.24.1"
lazygit = "0.54.2"
lefthook = "1.12.3"
neovim = "0.11.4"
node = "22.14.0"
peco = "0.5.11"
perl = "5.40.2"
pnpm = "10.15.1"
python = "3.13.7"
ruby = "3.4.5"
saml2aws = "2.36.19"
sops = "3.10.2"
task = "3.44.1"
terraform = "1.13.1"
tree-sitter = "0.25.8"
usage = "2.2.2"
yamlfmt = "0.17.2"
yq = "4.47.1"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
