[tools]
awscli = "2.31.13"
elixir = "1.18.3"
erlang = "27.3.3"
flutter = "3.29.3"
fzf = "0.65.2"
ghq = "1.8.0"
github-cli = "2.81.0"
go = "1.25.2"
lazydocker = "0.24.1"
lazygit = "0.55.1"
lefthook = "1.13.6"
neovim = "0.11.4"
node = "22.20.0"
peco = "0.5.11"
perl = "5.42.0"
pnpm = "10.18.2"
python = "3.14.0"
ruby = "3.4.7"
saml2aws = "2.36.19"
sops = "3.11.0"
task = "3.45.4"
terraform = "1.13.3"
tree-sitter = "0.25.10"
usage = "2.3.2"
yamlfmt = "0.17.2"
yq = "4.47.2"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
