[tools]
awscli = { version = "2.33.7", symlink_bins = "true" }
elixir = "1.19.5"
erlang = "28.3"
flutter = "3.38.7"
fzf = "0.67.0"
ghq = "1.8.0"
github-cli = "2.86.0"
go = "1.25.6"
lazydocker = "0.24.4"
lazygit = "0.58.1"
lefthook = "2.0.16"
neovim = "0.11.6"
node = "24.13.0"
peco = "0.5.11"
perl = "5.42.0"
pnpm = "10.28.2"
python = "3.14.2"
ruby = "4.0.1"
saml2aws = "2.36.19"
sops = "3.11.0"
task = "3.48.0"
terraform = "1.14.3"
tree-sitter = "0.26.3"
usage = "2.15.0"
yamlfmt = "0.21.0"
yq = "4.50.1"
zig = "0.15.2"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
