[tools]
awscli = "2.31.37"
elixir = "1.19.3"
erlang = "28.1.1"
flutter = "3.38.1"
fzf = "0.66.1"
ghq = "1.8.0"
github-cli = "2.83.1"
go = "1.25.4"
lazydocker = "0.24.2"
lazygit = "0.56.0"
lefthook = "1.13.6"
neovim = "0.11.5"
node = "24.11.1"
peco = "0.5.11"
perl = "5.42.0"
pnpm = "10.22.0"
python = "3.14.0"
ruby = "3.4.7"
saml2aws = "2.36.19"
sops = "3.11.0"
task = "3.45.5"
terraform = "1.13.5"
tree-sitter = "0.25.10"
usage = "2.8.0"
yamlfmt = "0.20.0"
yq = "4.48.2"
zig = "0.15.2"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
