[tools]
awscli = { version = "2.32.16", symlink_bins = "true" }
elixir = "1.19.4"
erlang = "28.3"
flutter = "3.38.5"
fzf = "0.67.0"
ghq = "1.8.0"
github-cli = "2.83.2"
go = "1.25.5"
lazydocker = "0.24.2"
lazygit = "0.57.0"
lefthook = "1.13.6"
neovim = "0.11.5"
node = "24.12.0"
peco = "0.5.11"
perl = "5.42.0"
pnpm = "10.25.0"
python = "3.14.2"
ruby = "3.4.7"
saml2aws = "2.36.19"
sops = "3.11.0"
task = "3.45.5"
terraform = "1.14.2"
tree-sitter = "0.26.3"
usage = "2.9.0"
yamlfmt = "0.20.0"
yq = "4.50.1"
zig = "0.15.2"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
